title: ReleaseHx Documentation
theme: just-the-docs
baseurl: /

plugins:
  - jekyll-asciidoc
  - jekyll-redirect-from

collections:
  releases:
    output: true
    permalink: /docs/releases/:name/

defaults:
  - scope:
      path: "docs/api"
    values:
      render_with_liquid: false
  - scope:
      path: ""
      type: "releases"
    values:
      layout: default
      nav_exclude: true

include:
  - index.adoc
  - config-reference.adoc

exclude:
  - manpage.adoc
  - jekyll/
  - payloads/
  - release/
  - yard/

# Enable Rouge for syntax highlighting in AsciiDoc blocks
asciidoctor:
  attributes:
    includedir: "{docdir}"
    source-highlighter: rouge

# Enable Just the Docs dark theme
color_scheme: dark

# Sass configuration
sass:
  sass_dir: jekyll/_sass
  quiet_deps: true
  silence_deprecations:
    - color-functions
    - import